USE master;
GO

CREATE LOGIN sample11_Alex WITH PASSWORD=N'Usr_2011#_Xls4168';
GO

CREATE LOGIN sample11_Lora WITH PASSWORD=N'Usr_2011#_Xls4168';
GO

CREATE LOGIN sample11_Nick WITH PASSWORD=N'Usr_2011#_Xls4168';
GO


CREATE USER sample11_Alex FOR LOGIN sample11_Alex WITH DEFAULT_SCHEMA=dbo;
GO

CREATE USER sample11_Lora FOR LOGIN sample11_Lora WITH DEFAULT_SCHEMA=dbo;
GO

CREATE USER sample11_Nick FOR LOGIN sample11_Nick WITH DEFAULT_SCHEMA=dbo;
GO

