DROP VIEW s08.AlphabeticalListOfProducts
DROP VIEW s08.CategorySalesFor1997
DROP VIEW s08.CurrentProductList
DROP VIEW s08.CustomerAndSuppliersByCity
DROP VIEW s08.Invoices
DROP VIEW s08.OrderDetailsExtended
DROP VIEW s08.OrdersQry
DROP VIEW s08.OrderSubtotals
DROP VIEW s08.ProductsAboveAveragePrice
DROP VIEW s08.ProductSalesFor1997
DROP VIEW s08.ProductsByCategory
DROP VIEW s08.QuarterlyOrders
DROP VIEW s08.SalesByCategory1997
DROP VIEW s08.SalesTotalsByAmount
DROP VIEW s08.SummaryOfSalesByQuarter
DROP VIEW s08.SummaryOfSalesByYear
